# Generated by Django 5.1 on 2026-03-27 11:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Adreces',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cp', models.CharField(max_length=10, verbose_name='Codi Postal')),
                ('poblacio', models.CharField(max_length=100, verbose_name='Població')),
                ('carrer', models.CharField(max_length=100, verbose_name='Carrer')),
                ('numero', models.CharField(max_length=10, verbose_name='Número')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='adreca', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
