# Generated by Django 5.1 on 2026-03-27 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuaris', '0002_perfilusuari'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PerfilUsuari',
        ),
    ]
