# Generated by Django 5.1 on 2026-04-08 22:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuaris', '0003_delete_perfilusuari'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adreces',
            name='user',
        ),
    ]
