# Generated by Django 5.1 on 2026-04-08 22:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuaris', '0004_remove_adreces_user'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='adreces',
            unique_together={('cp', 'poblacio', 'carrer', 'numero')},
        ),
    ]
