# Generated by Django 6.0.4 on 2026-04-21 14:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuaris', '0005_alter_adreces_unique_together'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UsuariAdreca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adreca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuaris_relacions', to='usuaris.adreces')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adreces_relacions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'adreca')},
            },
        ),
    ]
