# Generated by Django 6.0.4 on 2026-04-21 14:45

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuaris', '0006_usuariadreca'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UsuariAdreca',
            new_name='UsuariDireccio',
        ),
        migrations.RenameField(
            model_name='usuaridireccio',
            old_name='adreca',
            new_name='direccio',
        ),
        migrations.AlterUniqueTogether(
            name='usuaridireccio',
            unique_together={('user', 'direccio')},
        ),
    ]
