# Generated by Django 5.1 on 2026-03-21 11:13

import django.core.files.storage
import pathlib
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150)),
                ('tipus', models.CharField(choices=[('BLANC', 'Blanc'), ('NEGRE', 'Negre'), ('ESPUMOS', 'Espumos')], max_length=10)),
                ('preu', models.DecimalField(decimal_places=2, max_digits=8)),
                ('stock', models.IntegerField(default=0)),
                ('any_collita', models.IntegerField()),
                ('imatge', models.ImageField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(base_url='/static/vins/', location=pathlib.PurePosixPath('/home/daniel-rueda/Documentos/DAW/Projecte/projecte_vi/static/vins')), upload_to='')),
                ('descripcio', models.TextField()),
            ],
        ),
    ]
