# Generated by Django 5.1 on 2026-03-21 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vins', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vi',
            options={'verbose_name': 'Vi', 'verbose_name_plural': 'Vins'},
        ),
        migrations.AddField(
            model_name='vi',
            name='origen',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
    ]
