# Generated by Django 5.1 on 2026-03-21 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vins', '0002_alter_vi_options_vi_origen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vi',
            name='tipus',
            field=models.CharField(choices=[('BLANC', 'Blanc'), ('NEGRE', 'Negre'), ('ROSAT', 'Rosat'), ('ESPUMOS', 'Espumos')], max_length=10),
        ),
    ]
