# Generated by Django 5.1 on 2026-03-21 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vins', '0003_alter_vi_tipus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vi',
            name='imatge',
            field=models.ImageField(blank=True, null=True, upload_to='vins/'),
        ),
    ]
