# Generated by Django 5.1 on 2026-04-08 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vins', '0004_alter_vi_imatge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vi',
            name='origen',
            field=models.CharField(max_length=120),
        ),
    ]
