# Generated by Django 5.1 on 2026-04-08 21:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vins', '0005_alter_vi_origen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vi',
            name='any_collita',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1800), django.core.validators.MaxValueValidator(2026)]),
        ),
    ]
