# Generated by Django 6.0.4 on 2026-04-15 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vins', '0006_alter_vi_any_collita'),
    ]

    operations = [
        migrations.AddField(
            model_name='vi',
            name='es_actiu',
            field=models.BooleanField(default=True),
        ),
    ]
