# Generated by Django 6.0.4 on 2026-04-18 23:03

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vins', '0007_vi_es_actiu'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Carret',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unitats', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carret_items', to=settings.AUTH_USER_MODEL)),
                ('vi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carret_items', to='vins.vi')),
            ],
            options={
                'verbose_name': 'Item del carret',
                'verbose_name_plural': 'Items del carret',
                'unique_together': {('user', 'vi')},
            },
        ),
    ]
