# Generated by Django 6.0.4 on 2026-04-22 09:34

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comandes', '0001_initial'),
        ('usuaris', '0007_rename_usuariadreca_usuaridireccio_and_more'),
        ('vins', '0007_vi_es_actiu'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comanda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estat', models.CharField(choices=[('PENDENT', 'Pendent'), ('CONFIRMADA', 'Confirmada'), ('ENVIADA', 'Enviada'), ('ENTREGADA', 'Entregada'), ('CANCELLADA', 'Cancel·lada')], default='PENDENT', max_length=12)),
                ('data_creacio', models.DateTimeField(auto_now_add=True)),
                ('data_actualitzacio', models.DateTimeField(auto_now=True)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('direccio', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comandes', to='usuaris.adreces')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comandes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Comanda',
                'verbose_name_plural': 'Comandes',
                'ordering': ['-data_creacio'],
            },
        ),
        migrations.CreateModel(
            name='LineaComanda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unitats', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('preu_unitari', models.DecimalField(decimal_places=2, max_digits=8)),
                ('comanda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='linies', to='comandes.comanda')),
                ('vi', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linies_comanda', to='vins.vi')),
            ],
            options={
                'verbose_name': 'Línia de comanda',
                'verbose_name_plural': 'Línies de comanda',
            },
        ),
    ]
